import { SubtitleItem, SubtitleStyleConfig, BlurOverlay, LogoOverlay, TextOverlay } from '../types';
import { wrapSubtitleText } from './srtParser';
import { generateVoiceoverAudioBuffer } from './audioExporter';
import { createFile as createMp4BoxFile, DataStream } from 'mp4box';
import fixWebmDuration from 'fix-webm-duration';

function createMp4File() {
  return createMp4BoxFile();
}

/**
 * Fixes duration metadata in MP4 files (mvhd, tkhd, mdhd, mehd boxes)
 * generated by MediaRecorder or encoders that omit or zero duration metadata.
 */
export async function fixMp4Duration(blob: Blob, durationInSeconds: number): Promise<Blob> {
  if (!durationInSeconds || durationInSeconds <= 0) return blob;

  try {
    const arrayBuffer = await blob.arrayBuffer();
    const bytes = new Uint8Array(arrayBuffer);
    const view = new DataView(arrayBuffer);

    let movieTimescale = 1000;

    function scanBoxes(start: number, end: number) {
      let pos = start;
      while (pos + 8 <= end) {
        let boxSize = view.getUint32(pos);
        const boxType = String.fromCharCode(
          bytes[pos + 4],
          bytes[pos + 5],
          bytes[pos + 6],
          bytes[pos + 7]
        );

        let headerSize = 8;
        if (boxSize === 1) {
          if (pos + 16 > end) break;
          const high = view.getUint32(pos + 8);
          const low = view.getUint32(pos + 12);
          boxSize = high * 4294967296 + low;
          headerSize = 16;
        } else if (boxSize === 0) {
          boxSize = end - pos;
        }

        if (boxSize < headerSize || pos + boxSize > end) {
          break;
        }

        const payloadStart = pos + headerSize;
        const payloadEnd = pos + boxSize;

        if (
          boxType === 'moov' ||
          boxType === 'trak' ||
          boxType === 'mdia' ||
          boxType === 'minf' ||
          boxType === 'mvex'
        ) {
          scanBoxes(payloadStart, payloadEnd);
        } else if (boxType === 'mvhd') {
          const version = bytes[payloadStart];
          let timescaleOffset = payloadStart + 12;
          let durationOffset = payloadStart + 16;
          if (version === 1) {
            timescaleOffset = payloadStart + 20;
            durationOffset = payloadStart + 24;
          }
          if (timescaleOffset + 4 <= payloadEnd) {
            movieTimescale = view.getUint32(timescaleOffset) || 1000;
          }
          const targetDurationUnits = Math.round(durationInSeconds * movieTimescale);

          if (version === 0 && durationOffset + 4 <= payloadEnd) {
            view.setUint32(durationOffset, targetDurationUnits);
          } else if (version === 1 && durationOffset + 8 <= payloadEnd) {
            const high = Math.floor(targetDurationUnits / 4294967296);
            const low = targetDurationUnits % 4294967296;
            view.setUint32(durationOffset, high);
            view.setUint32(durationOffset + 4, low);
          }
        } else if (boxType === 'tkhd') {
          const version = bytes[payloadStart];
          let durationOffset = payloadStart + 20;
          if (version === 1) {
            durationOffset = payloadStart + 28;
          }
          const targetDurationUnits = Math.round(durationInSeconds * movieTimescale);

          if (version === 0 && durationOffset + 4 <= payloadEnd) {
            view.setUint32(durationOffset, targetDurationUnits);
          } else if (version === 1 && durationOffset + 8 <= payloadEnd) {
            const high = Math.floor(targetDurationUnits / 4294967296);
            const low = targetDurationUnits % 4294967296;
            view.setUint32(durationOffset, high);
            view.setUint32(durationOffset + 4, low);
          }
        } else if (boxType === 'mdhd') {
          const version = bytes[payloadStart];
          let timescaleOffset = payloadStart + 12;
          let durationOffset = payloadStart + 16;
          if (version === 1) {
            timescaleOffset = payloadStart + 20;
            durationOffset = payloadStart + 24;
          }
          let mediaTimescale = movieTimescale;
          if (timescaleOffset + 4 <= payloadEnd) {
            mediaTimescale = view.getUint32(timescaleOffset) || movieTimescale;
          }
          const targetDurationUnits = Math.round(durationInSeconds * mediaTimescale);

          if (version === 0 && durationOffset + 4 <= payloadEnd) {
            view.setUint32(durationOffset, targetDurationUnits);
          } else if (version === 1 && durationOffset + 8 <= payloadEnd) {
            const high = Math.floor(targetDurationUnits / 4294967296);
            const low = targetDurationUnits % 4294967296;
            view.setUint32(durationOffset, high);
            view.setUint32(durationOffset + 4, low);
          }
        } else if (boxType === 'mehd') {
          const version = bytes[payloadStart];
          const durationOffset = payloadStart + 4;
          const targetDurationUnits = Math.round(durationInSeconds * movieTimescale);

          if (version === 0 && durationOffset + 4 <= payloadEnd) {
            view.setUint32(durationOffset, targetDurationUnits);
          } else if (version === 1 && durationOffset + 8 <= payloadEnd) {
            const high = Math.floor(targetDurationUnits / 4294967296);
            const low = targetDurationUnits % 4294967296;
            view.setUint32(durationOffset, high);
            view.setUint32(durationOffset + 4, low);
          }
        }

        pos += boxSize;
      }
    }

    scanBoxes(0, bytes.length);
    return new Blob([bytes.buffer], { type: blob.type || 'video/mp4' });
  } catch (err) {
    console.warn('[fixMp4Duration] Failed to patch MP4 duration:', err);
    return blob;
  }
}

/**
 * Adjusts volume of an AudioBuffer using OfflineAudioContext.
 */
async function adjustAudioBufferVolume(
  original: AudioBuffer | null,
  volume: number = 1.0,
  targetDuration: number
): Promise<AudioBuffer | null> {
  if (!original) return null;
  if (volume === 0) return null; // Muted
  if (volume === 1.0) return original; // No change needed

  const sampleRate = original.sampleRate;
  const numChannels = original.numberOfChannels;
  const duration = Math.max(original.duration, targetDuration);

  const offlineCtx = new OfflineAudioContext(
    numChannels,
    Math.ceil(sampleRate * duration),
    sampleRate
  );

  const originalSource = offlineCtx.createBufferSource();
  originalSource.buffer = original;

  const gainNode = offlineCtx.createGain();
  gainNode.gain.value = volume;

  originalSource.connect(gainNode);
  gainNode.connect(offlineCtx.destination);
  originalSource.start(0);

  return await offlineCtx.startRendering();
}

/**
 * Mixes original video audio and TTS voiceover audio together.
 */
async function mixAudioBuffers(
  original: AudioBuffer | null,
  tts: AudioBuffer | null,
  targetDuration: number,
  videoVolume: number = 1.0
): Promise<AudioBuffer | null> {
  if (!original && !tts) return null;
  if (original && !tts) {
    return await adjustAudioBufferVolume(original, videoVolume, targetDuration);
  }
  if (!original && tts) return tts;

  // Both original and TTS exist
  if (videoVolume === 0) {
    return tts;
  }

  const sampleRate = original!.sampleRate;
  const numChannels = Math.max(original!.numberOfChannels, tts!.numberOfChannels);
  const duration = Math.max(original!.duration, tts!.duration, targetDuration);

  const offlineCtx = new OfflineAudioContext(
    numChannels,
    Math.ceil(sampleRate * duration),
    sampleRate
  );

  // 1. Play original audio with videoVolume applied
  const originalSource = offlineCtx.createBufferSource();
  originalSource.buffer = original!;

  if (videoVolume !== 1.0) {
    const gainNode = offlineCtx.createGain();
    gainNode.gain.value = videoVolume;
    originalSource.connect(gainNode);
    gainNode.connect(offlineCtx.destination);
  } else {
    originalSource.connect(offlineCtx.destination);
  }
  originalSource.start(0);

  // 2. Play TTS audio (mono will be automatically upmixed to stereo/numChannels)
  const ttsSource = offlineCtx.createBufferSource();
  ttsSource.buffer = tts!;
  ttsSource.connect(offlineCtx.destination);
  ttsSource.start(0);

  return await offlineCtx.startRendering();
}

export interface RenderProgress {
  percentage: number;
  currentTime: number;
  duration: number;
  status: string;
}

/**
 * Draws current video frame and burning subtitle overlay onto the 2D Canvas context.
 */
function wrapCanvasText(
  context: CanvasRenderingContext2D,
  text: string,
  maxWidth: number
): string[] {
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let currentLine = '';

  for (let i = 0; i < words.length; i++) {
    const word = words[i];
    const testLine = currentLine ? currentLine + ' ' + word : word;
    const metrics = context.measureText(testLine);
    if (metrics.width > maxWidth && i > 0) {
      lines.push(currentLine);
      currentLine = word;
    } else {
      currentLine = testLine;
    }
  }
  if (currentLine) {
    lines.push(currentLine);
  }
  return lines;
}

function getBgColorWithOpacity(hexColor: string, opacity: number = 65): string {
  if (!hexColor) return `rgba(0, 0, 0, ${opacity / 100})`;
  if (hexColor.startsWith('rgba')) return hexColor;
  let hex = hexColor.replace('#', '');
  if (hex.length === 3) hex = hex.split('').map(x => x + x).join('');
  const num = parseInt(hex, 16);
  if (isNaN(num)) return `rgba(0, 0, 0, ${opacity / 100})`;
  const r = (num >> 16) & 255;
  const g = (num >> 8) & 255;
  const b = num & 255;
  return `rgba(${r}, ${g}, ${b}, ${(opacity / 100).toFixed(2)})`;
}

export function drawSubtitleOverlay(
  ctx: CanvasRenderingContext2D,
  video: HTMLVideoElement,
  vWidth: number,
  vHeight: number,
  curTime: number,
  subtitles: SubtitleItem[],
  styleConfig: SubtitleStyleConfig,
  blurOverlays: BlurOverlay[] = [],
  logoOverlays: LogoOverlay[] = [],
  textOverlays: TextOverlay[] = [],
  logoBitmaps: Record<string, HTMLImageElement | ImageBitmap> = {}
) {
  // 1. Draw base video frame
  ctx.drawImage(video, 0, 0, vWidth, vHeight);

  // 1b. Render Blur Overlays
  blurOverlays.forEach((blur) => {
    try {
      ctx.save();
      ctx.beginPath();
      const x = (blur.x / 100) * vWidth;
      const y = (blur.y / 100) * vHeight;
      const w = (blur.width / 100) * vWidth;
      const h = (blur.height / 100) * vHeight;
      const r = (blur.borderRadius || 0) * (vHeight / 720);
      if (typeof ctx.roundRect === 'function') {
        ctx.roundRect(x, y, w, h, r);
      } else {
        ctx.rect(x, y, w, h);
      }
      ctx.clip();
      ctx.filter = `blur(${blur.blur * (vHeight / 720)}px)`;
      ctx.drawImage(video, 0, 0, vWidth, vHeight);
      ctx.restore();
    } catch (err) {
      console.warn('[VideoRenderer] Blur overlay draw warning:', err);
    }
  });

  // 1c. Render Logo Overlays
  logoOverlays.forEach((logo) => {
    const x = (logo.x / 100) * vWidth;
    const y = (logo.y / 100) * vHeight;
    const w = (logo.width / 100) * vWidth;
    const h = (logo.height / 100) * vHeight;
    const img = logoBitmaps[logo.id] || logoBitmaps[logo.url];
    if (img) {
      ctx.save();
      ctx.globalAlpha = (logo.opacity || 100) / 100;
      ctx.drawImage(img, x, y, w, h);
      ctx.restore();
    }
  });

  // 1d. Render Text Overlays
  textOverlays.forEach((textItem) => {
    const x = (textItem.x / 100) * vWidth;
    const y = (textItem.y / 100) * vHeight;
    const w = (textItem.width / 100) * vWidth;
    const h = (textItem.height / 100) * vHeight;
    ctx.save();
    ctx.globalAlpha = (textItem.opacity || 100) / 100;
    if (textItem.backgroundColor) {
      ctx.fillStyle = textItem.backgroundColor;
      ctx.fillRect(x, y, w, h);
    }
    // Scale font size dynamically with height
    const scaleFactor = vHeight / 720;
    const fontSize = Math.max(8, Math.round(textItem.fontSize * scaleFactor));
    const fontFamily = styleConfig.fontFamily || 'system-ui, sans-serif';
    ctx.font = `bold ${fontSize}px ${fontFamily}`;
    ctx.fillStyle = textItem.color || '#ffffff';
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';

    const textLines = wrapCanvasText(ctx, textItem.text, w - 8);
    const textLineHeight = fontSize * 1.2;
    const startY = y + h / 2 - ((textLines.length - 1) * textLineHeight) / 2;
    textLines.forEach((line, idx) => {
      ctx.fillText(line, x + w / 2, startY + idx * textLineHeight);
    });
    ctx.restore();
  });

  // 2. Mask original subtitles if requested
  if (styleConfig.maskOriginalSubtitles) {
    ctx.fillStyle = styleConfig.maskColor || 'rgba(0, 0, 0, 0.75)';
    const maskY =
      vHeight * (1 - (styleConfig.bottomOffsetPercentage || 12) / 100) -
      vHeight * 0.08;
    const maskH = vHeight * 0.14;
    ctx.fillRect(0, Math.max(0, maskY), vWidth, maskH);
  }

  // 3. Find active subtitle item
  const activeSub = subtitles.find(
    (s) => curTime >= s.startTime && curTime <= s.endTime
  );

  if (!activeSub) return;

  let rawText = activeSub.translatedText || activeSub.originalText || '';

  // Apply text transformation (casing)
  if (styleConfig.textTransform === 'uppercase') {
    rawText = rawText.toUpperCase();
  } else if (styleConfig.textTransform === 'lowercase') {
    rawText = rawText.toLowerCase();
  } else if (styleConfig.textTransform === 'capitalize') {
    rawText = rawText.replace(/\b\w/g, (c) => c.toUpperCase());
  }

  // Align style configurations & fallback defaults with VideoPlayer.tsx perfectly
  const defaultFontSize = styleConfig.fontSize || 22;
  const defaultPadding = styleConfig.padding || 6;
  const defaultBorderRadius = styleConfig.borderRadius ?? 8;
  const bgOpacity = styleConfig.bgOpacity ?? 65;

  // Calculate font size relative to standard 720p height
  const scaleFactor = vHeight / 720;
  const baseFontSize = defaultFontSize * scaleFactor;
  // Proportional minimum font size (10px on 360p corresponds to 20px on 720p)
  const minFontSize = Math.max(12, Math.round(20 * scaleFactor));
  const fontSize = Math.max(minFontSize, Math.round(baseFontSize));

  const fontFamily = styleConfig.fontFamily || 'system-ui, sans-serif';
  const fontWeight = styleConfig.fontWeight || 'bold';
  const fontStyle = styleConfig.fontStyle || 'normal';

  ctx.font = `${fontStyle} ${fontWeight} ${fontSize}px ${fontFamily}`;
  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';

  const lineHeight = fontSize * 1.35;
  const padding = defaultPadding * scaleFactor;

  // Use boundingBox if available, otherwise fallback
  const displayBox = activeSub.boundingBox;
  
  let lines: string[];
  let boxX: number;
  let boxY: number;
  let boxWidth: number;
  let boxHeight: number;

  if (displayBox) {
    const parentX = (displayBox.x / 100) * vWidth;
    const parentY = (displayBox.y / 100) * vHeight;
    const parentWidth = (displayBox.width / 100) * vWidth;
    const parentHeight = (displayBox.height / 100) * vHeight;

    // Word wrap based on bounding box width
    const wrapWidth = Math.max(50, parentWidth - padding * 2.5);
    lines = wrapCanvasText(ctx, rawText, wrapWidth);

    // Calculate actual content dimensions
    let maxLineWidth = 0;
    lines.forEach((line) => {
      const w = ctx.measureText(line).width;
      if (w > maxLineWidth) maxLineWidth = w;
    });

    const totalTextHeight = lines.length * lineHeight;
    boxWidth = Math.min(parentWidth, maxLineWidth + padding * 2.5);
    boxHeight = Math.min(parentHeight, totalTextHeight + padding * 1.5);

    // Center content box inside parent bounding box
    boxX = parentX + (parentWidth - boxWidth) / 2;
    boxY = parentY + (parentHeight - boxHeight) / 2;
  } else {
    // Fallback wrapping based on max character width
    const wrappedText = wrapSubtitleText(
      rawText,
      styleConfig.orientation || 'horizontal',
      styleConfig.maxCharsHorizontal || 65,
      styleConfig.maxCharsVertical || 36
    );
    lines = wrappedText ? wrappedText.split('\n') : [];
    if (lines.length === 0) return;

    let maxLineWidth = 0;
    lines.forEach((line) => {
      const w = ctx.measureText(line).width;
      if (w > maxLineWidth) maxLineWidth = w;
    });

    const totalTextHeight = lines.length * lineHeight;
    boxWidth = maxLineWidth + padding * 2.5;
    boxHeight = totalTextHeight + padding * 1.5;

    let posY = vHeight * 0.82;
    if (styleConfig.position === 'top') {
      posY = vHeight * 0.15;
    } else if (styleConfig.position === 'middle') {
      posY = vHeight * 0.5;
    }
    if (styleConfig.bottomOffsetPercentage) {
      posY = vHeight * (1 - styleConfig.bottomOffsetPercentage / 100);
    }

    boxX = (vWidth - boxWidth) / 2;
    boxY = posY - boxHeight / 2;
  }

  // Draw Subtitle Background Box with proper alpha/opacity parsing
  if (styleConfig.hasBackground !== false && styleConfig.backgroundColor) {
    ctx.fillStyle = getBgColorWithOpacity(styleConfig.backgroundColor, bgOpacity);
    const radius = defaultBorderRadius * scaleFactor;

    ctx.beginPath();
    if (typeof ctx.roundRect === 'function') {
      ctx.roundRect(boxX, boxY, boxWidth, boxHeight, radius);
    } else {
      ctx.rect(boxX, boxY, boxWidth, boxHeight);
    }
    ctx.fill();
  }

  // Draw Text Lines centered inside box
  const startY = boxY + boxHeight / 2 - ((lines.length - 1) * lineHeight) / 2;
  const drawX = boxX + boxWidth / 2;

  lines.forEach((line, idx) => {
    const lineY = startY + idx * lineHeight;

    // 1. Text Shadow / Glow
    if (styleConfig.textShadowColor) {
      ctx.save();
      ctx.shadowColor = styleConfig.textShadowColor;
      ctx.shadowBlur = (styleConfig.textShadowBlur ?? 8) * scaleFactor;
      ctx.shadowOffsetX = (styleConfig.textShadowOffsetX ?? 0) * scaleFactor;
      ctx.shadowOffsetY = (styleConfig.textShadowOffsetY ?? 2) * scaleFactor;
      ctx.fillStyle = styleConfig.fontColor || '#ffffff';
      ctx.fillText(line, drawX, lineY);
      ctx.restore();
    } else if (styleConfig.textOutline !== false) {
      ctx.save();
      ctx.shadowColor = 'rgba(0,0,0,0.85)';
      ctx.shadowBlur = 6 * scaleFactor;
      ctx.shadowOffsetY = 3 * scaleFactor;
      ctx.fillStyle = styleConfig.fontColor || '#ffffff';
      ctx.fillText(line, drawX, lineY);
      ctx.restore();
    }

    // 2. Secondary Text Outline (Viền kép / Outer sticker border)
    const hasSecOutline = styleConfig.hasSecondaryOutline === true ||
      (typeof styleConfig.secondaryOutlineWidth === 'number' && styleConfig.secondaryOutlineWidth > 0 && styleConfig.hasSecondaryOutline !== false);
    const secOutlineWidth = hasSecOutline ? Math.max(0, styleConfig.secondaryOutlineWidth ?? 4) : 0;
    const primOutlineWidth = (styleConfig.textOutline !== false) ? Math.max(0, styleConfig.outlineWidth ?? 3) : 0;

    if (secOutlineWidth > 0) {
      const totalSecStroke = Math.max(0.5, (primOutlineWidth + secOutlineWidth) * 2 * scaleFactor);
      ctx.strokeStyle = styleConfig.secondaryOutlineColor || '#000000';
      ctx.lineWidth = totalSecStroke;
      ctx.lineJoin = 'round';
      ctx.miterLimit = 2;
      ctx.strokeText(line, drawX, lineY);
    }

    // 3. Primary Text Outline (Stroke)
    if (styleConfig.textOutline !== false && primOutlineWidth > 0) {
      ctx.strokeStyle = styleConfig.outlineColor || '#000000';
      ctx.lineWidth = Math.max(0.5, primOutlineWidth * 2 * scaleFactor);
      ctx.lineJoin = 'round';
      ctx.miterLimit = 2;
      ctx.strokeText(line, drawX, lineY);
    }

    // 4. Main Text Fill
    ctx.fillStyle = styleConfig.fontColor || '#ffffff';
    ctx.fillText(line, drawX, lineY);
  });
}

/**
 * Renders video with subtitles using Mediabunny, WebCodecs API, OffscreenCanvas, and a background Web Worker.
 */
export async function renderWithMp4Muxer(
  videoUrl: string,
  subtitles: SubtitleItem[],
  styleConfig: SubtitleStyleConfig,
  onProgress: (progress: RenderProgress) => void,
  options: {
    blurOverlays?: BlurOverlay[];
    logoOverlays?: LogoOverlay[];
    textOverlays?: TextOverlay[];
    includeVoiceover?: boolean;
    ttsSpeed?: number;
    ttsPitch?: number;
    videoVolume?: number;
  } = {},
  preferSoftware = false
): Promise<Blob> {
  if (typeof VideoEncoder === 'undefined') {
    throw new Error('WebCodecs VideoEncoder không được hỗ trợ trên trình duyệt này.');
  }

  // 1. Fetch the video as an ArrayBuffer once
  let arrayBuffer: ArrayBuffer;
  try {
    const res = await fetch(videoUrl);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    arrayBuffer = await res.arrayBuffer();
  } catch (err) {
    throw new Error(`CORS hoặc network error khi tải video ArrayBuffer: ${String(err)}`);
  }

  // 2. Load HTMLVideoElement to read duration and original metadata
  const video = document.createElement('video');
  if (videoUrl && !videoUrl.startsWith('blob:')) {
    video.crossOrigin = 'anonymous';
  }
  video.muted = true;
  video.src = videoUrl;

  await new Promise((res, rej) => {
    video.onloadedmetadata = res;
    video.onerror = () => rej(new Error('Không thể tải video nguồn để render.'));
  });

  const toEven = (val: number) => Math.max(2, Math.floor(val / 2) * 2);
  const rawWidth = video.videoWidth || 1280;
  const rawHeight = video.videoHeight || 720;
  const vWidth = toEven(rawWidth);
  const vHeight = toEven(rawHeight);
  const duration = video.duration || 10;

  // 3. Decode Original Audio (if present)
  let originalAudioBuffer: AudioBuffer | null = null;
  try {
    const actx = new (window.AudioContext || (window as any).webkitAudioContext)();
    const decodeBuf = arrayBuffer.slice(0);
    originalAudioBuffer = await actx.decodeAudioData(decodeBuf);
    await actx.close();
  } catch (e) {
    console.warn('Không có hoặc không thể nạp audio track gốc:', e);
  }

  // 4. Generate or Mix Audio
  const videoVolume = options.videoVolume ?? 1.0;
  let audioBuffer: AudioBuffer | null = null;
  if (options.includeVoiceover) {
    try {
      const result = await generateVoiceoverAudioBuffer(
        subtitles,
        duration,
        options.ttsSpeed || 1.0,
        options.ttsPitch || 0
      );
      const ttsAudioBuffer = result.buffer;
      console.log(`[Audio Render] Dựng thành công audio thuyết minh (${result.count} clips, duration: ${result.totalDuration}s)`);
      
      // Mix original audio and TTS audio together with videoVolume
      audioBuffer = await mixAudioBuffers(originalAudioBuffer, ttsAudioBuffer, duration, videoVolume);
    } catch (e: any) {
      console.warn('Không thể dựng audio thuyết minh, sẽ dùng audio gốc làm fallback:', e);
      audioBuffer = await adjustAudioBufferVolume(originalAudioBuffer, videoVolume, duration);
    }
  } else {
    audioBuffer = await adjustAudioBufferVolume(originalAudioBuffer, videoVolume, duration);
  }

  // Compute dynamic bitrate based on target dimensions
  const getDynamicBitrate = (width: number, height: number): number => {
    const pixels = width * height;
    if (pixels >= 3840 * 2160) return 20_000_000; // 4K -> 20 Mbps
    if (pixels >= 2560 * 1440) return 10_000_000; // 2K -> 10 Mbps
    if (pixels >= 1920 * 1080) return 5_000_000;  // 1080p -> 5 Mbps
    if (pixels >= 1280 * 720) return 2_500_000;   // 720p -> 2.5 Mbps
    return 1_200_000;                             // 480p/lower -> 1.2 Mbps
  };
  const dynamicBitrate = getDynamicBitrate(vWidth, vHeight);

  // Helper to determine resolution-aware H.264 / VP9 codec candidate list
  const getCodecCandidates = (w: number, h: number, preferSoft: boolean) => {
    const maxDim = Math.max(w, h);
    if (maxDim > 1920) {
      return [
        { codec: 'avc1.640033', muxer: 'avc' as const }, // High Profile Level 5.1 (4K)
        { codec: 'avc1.4d0033', muxer: 'avc' as const }, // Main Profile Level 5.1
        { codec: 'avc1.4d002a', muxer: 'avc' as const }, // Main Profile Level 4.2
        { codec: 'vp09.00.10.08', muxer: 'vp9' as const },
      ];
    } else if (maxDim >= 1080) {
      return preferSoft ? [
        { codec: 'avc1.4d002a', muxer: 'avc' as const }, // Main Profile Level 4.2 (1080p compatible)
        { codec: 'avc1.42002a', muxer: 'avc' as const }, // Baseline Profile Level 4.2
        { codec: 'avc1.64002a', muxer: 'avc' as const }, // High Profile Level 4.2
        { codec: 'vp09.00.10.08', muxer: 'vp9' as const },
      ] : [
        { codec: 'avc1.4d002a', muxer: 'avc' as const }, // Main Profile Level 4.2 (Standard Web MP4)
        { codec: 'avc1.64002a', muxer: 'avc' as const }, // High Profile Level 4.2
        { codec: 'avc1.42002a', muxer: 'avc' as const }, // Baseline Profile Level 4.2
        { codec: 'vp09.00.10.08', muxer: 'vp9' as const },
      ];
    } else {
      return [
        { codec: 'avc1.4d001f', muxer: 'avc' as const }, // Main Profile Level 3.1 (720p)
        { codec: 'avc1.42001f', muxer: 'avc' as const }, // Baseline Profile Level 3.1
        { codec: 'avc1.42002a', muxer: 'avc' as const }, // Baseline Profile Level 4.2
        { codec: 'vp09.00.10.08', muxer: 'vp9' as const },
      ];
    }
  };

  // Determine supported H.264/AVC or VP9 codec using candidates suitable for HD/4K resolutions
  const hwAccelMode = preferSoftware ? 'prefer-software' : 'no-preference';
  const codecCandidates = getCodecCandidates(vWidth, vHeight, preferSoftware);

  let videoCodec = codecCandidates[0].codec;
  let muxerVideoCodec: 'avc' | 'hevc' | 'vp9' | 'av1' = codecCandidates[0].muxer;
  let foundSupportedCodec = false;

  for (const cand of codecCandidates) {
    try {
      const check = await VideoEncoder.isConfigSupported({
        codec: cand.codec,
        width: vWidth,
        height: vHeight,
        bitrate: dynamicBitrate,
        framerate: 30,
        hardwareAcceleration: hwAccelMode,
      });
      if (check.supported) {
        videoCodec = cand.codec;
        muxerVideoCodec = cand.muxer;
        foundSupportedCodec = true;
        console.log(`[Video Render Codec Probing] Codec: ${videoCodec} | Muxer: ${muxerVideoCodec} | Mode: ${hwAccelMode}`);
        break;
      }
    } catch (_e) {}
  }

  // Proactive Probing Fallback: If hardware probing failed for all profiles, retry with prefer-software
  if (!foundSupportedCodec && !preferSoftware) {
    console.warn('[Video Render Codec Probing] No hardware acceleration candidates supported, probing prefer-software...');
    const softCandidates = getCodecCandidates(vWidth, vHeight, true);
    for (const cand of softCandidates) {
      try {
        const check = await VideoEncoder.isConfigSupported({
          codec: cand.codec,
          width: vWidth,
          height: vHeight,
          bitrate: dynamicBitrate,
          framerate: 30,
          hardwareAcceleration: 'prefer-software',
        });
        if (check.supported) {
          videoCodec = cand.codec;
          muxerVideoCodec = cand.muxer;
          foundSupportedCodec = true;
          console.log(`[Video Render Codec Probing Fallback] Codec: ${videoCodec} | Muxer: ${muxerVideoCodec} | Mode: prefer-software`);
          break;
        }
      } catch (_e) {}
    }
  }

  let audioMuxerCodec: 'aac' | 'opus' = 'aac';
  let audioCodecStr = 'mp4a.40.2';
  let canEncodeAudio = false;

  if (audioBuffer && typeof AudioEncoder !== 'undefined') {
    const sampleRate = audioBuffer.sampleRate;
    const channels = Math.min(2, audioBuffer.numberOfChannels);

    let aacSupported = false;
    try {
      const aacCheck = await AudioEncoder.isConfigSupported({
        codec: 'mp4a.40.2',
        numberOfChannels: channels,
        sampleRate: sampleRate,
        bitrate: 128_000,
      });
      aacSupported = !!aacCheck.supported;
    } catch {}

    if (aacSupported) {
      audioMuxerCodec = 'aac';
      audioCodecStr = 'mp4a.40.2';
      canEncodeAudio = true;
    } else {
      let opusSupported = false;
      try {
        const opusCheck = await AudioEncoder.isConfigSupported({
          codec: 'opus',
          numberOfChannels: channels,
          sampleRate: sampleRate,
          bitrate: 128_000,
        });
        opusSupported = !!opusCheck.supported;
      } catch {}
      if (opusSupported) {
        audioCodecStr = 'opus';
        audioMuxerCodec = 'opus';
        canEncodeAudio = true;
      }
    }
  }

  return new Promise(async (resolve, reject) => {
    let worker: Worker | null = null;
    let completedFramesMap: Map<number, {
      renderedBitmap: ImageBitmap;
      timestampUs: number;
      isKeyFrame: boolean;
      currentTime: number;
    }> | null = null;
    let taskWorkers: Worker[] = [];
    let watchdogInterval: ReturnType<typeof setInterval> | undefined = undefined;

    try {
      // 1. Demux first to get actual frame count and calculate average FPS
      const mp4File = createMp4File();
      let videoTrack: any = null;
      let decoderConfig: VideoDecoderConfig | null = null;
      const accumulatedSamples: any[] = [];

      mp4File.onReady = (info: any) => {
        if (!info.videoTracks || info.videoTracks.length === 0) {
          reject(new Error('Không tìm thấy luồng Video Track trong tệp MP4.'));
          return;
        }

        videoTrack = info.videoTracks[0];

        let description: Uint8Array | undefined = undefined;
        try {
          const trak = mp4File.getTrackById(videoTrack.id);
          if (trak?.mdia?.minf?.stbl?.stsd?.entries?.[0]) {
            const entry = trak.mdia.minf.stbl.stsd.entries[0];
            const box = entry.avcC || entry.hvcC || entry.vpcC || entry.av1C;
            if (box) {
              const stream = new DataStream(undefined, 0, DataStream.BIG_ENDIAN);
              box.write(stream);
              description = new Uint8Array(stream.buffer, 8);
            }
          }
        } catch (_e) {}

        decoderConfig = {
          codec: videoTrack.codec,
          codedWidth: videoTrack.video.width,
          codedHeight: videoTrack.video.height,
          description,
          hardwareAcceleration: preferSoftware ? 'prefer-software' : 'no-preference',
          optimizeForLatency: false,
        } as any;

        // Smooth chunk loading to prevent massive extraction bursts
        mp4File.setExtractionOptions(videoTrack.id, null, { nbSamples: 1000 });
        mp4File.start();
      };

      mp4File.onSamples = (id: number, user: any, samples: any[]) => {
        accumulatedSamples.push(...samples);
      };

      mp4File.onError = (e: any) => reject(e);

      // Perform buffer demuxing synchronously
      (arrayBuffer as any).fileStart = 0;
      mp4File.appendBuffer(arrayBuffer);
      mp4File.flush();

      // Sort accumulated samples by dts (or cts) to ensure decoding order is monotonic
      accumulatedSamples.sort((a, b) => (a.dts ?? a.cts) - (b.dts ?? b.cts));

      // Ensure we have demuxed all samples successfully
      const totalFrames = accumulatedSamples.length;
      if (totalFrames === 0) {
        reject(new Error('Không giải nén được khung hình nào từ video nguồn.'));
        return;
      }

      if (!decoderConfig) {
        reject(new Error('Thiếu cấu hình VideoDecoder sau khi demuxing.'));
        return;
      }

      // Calculate the exact video frame rate (FPS) from track timescale and sample count
      let videoFps = 30;
      if (videoTrack?.timescale && videoTrack?.duration && videoTrack?.nb_samples) {
        const trackDurationSec = videoTrack.duration / videoTrack.timescale;
        if (trackDurationSec > 0) {
          videoFps = videoTrack.nb_samples / trackDurationSec;
        }
      }
      if (!videoFps || !isFinite(videoFps) || videoFps <= 5 || videoFps > 120) {
        videoFps = Math.max(10, Math.min(60, totalFrames / duration)) || 30;
      }
      console.log(`[Video Render FPS Calculation] Total frames: ${totalFrames}, calculated FPS: ${videoFps.toFixed(3)}`);

      // 2. Instantiate Web Worker
      worker = new Worker(
        new URL('../workers/videoRenderer.worker.ts', import.meta.url),
        { type: 'module' }
      );

      const initWorkerPromise = new Promise<void>((resolveInit, rejectInit) => {
        if (!worker) return rejectInit(new Error('Khởi tạo Web Worker thất bại'));
        const initListener = (msg: MessageEvent) => {
          if (msg.data.type === 'INIT_SUCCESS') {
            worker?.removeEventListener('message', initListener);
            resolveInit();
          } else if (msg.data.type === 'ERROR') {
            worker?.removeEventListener('message', initListener);
            rejectInit(new Error(msg.data.error || 'Lỗi khởi tạo Web Worker'));
          }
        };
        worker.addEventListener('message', initListener);
      });

      let hasWorkerError = false;
      let workerErrorMessage = '';

      const workerPromise = new Promise<Blob>((resWorker, rejWorker) => {
        if (!worker) return rejWorker(new Error('Khởi tạo Web Worker thất bại'));

        worker.onmessage = (msg: MessageEvent) => {
          const { type, percentage, currentTime: cTime, status, buffer, error } = msg.data;

          if (type === 'PROGRESS') {
            onProgress({
              percentage: percentage || 0,
              currentTime: cTime || 0,
              duration,
              status: status || 'Đang xử lý trong Web Worker...',
            });
          } else if (type === 'COMPLETE') {
            const finalBlob = msg.data.blob || new Blob([msg.data.buffer], { type: 'video/mp4' });
            resWorker(finalBlob);
          } else if (type === 'ERROR') {
            hasWorkerError = true;
            workerErrorMessage = error || 'Lỗi trong Web Worker';
            rejWorker(new Error(workerErrorMessage));
            if (typeof watchdogInterval !== 'undefined') clearInterval(watchdogInterval);
            taskWorkers.forEach(tw => tw.terminate());
            reject(new Error(workerErrorMessage));
          }
        };

        worker.onerror = (err) => {
          hasWorkerError = true;
          workerErrorMessage = err?.message || 'Worker execution error';
          rejWorker(new Error(workerErrorMessage));
          if (typeof watchdogInterval !== 'undefined') clearInterval(watchdogInterval);
          taskWorkers.forEach(tw => tw.terminate());
          reject(new Error(workerErrorMessage));
        };
      });

      // Send INIT to Worker with dynamic bitrate and calculated framerate
      worker.postMessage({
        type: 'INIT',
        vWidth,
        vHeight,
        videoCodec,
        muxerVideoCodec,
        bitrate: dynamicBitrate,
        framerate: videoFps,
        preferSoftware,
        audioConfig:
          canEncodeAudio && audioBuffer
            ? {
                audioCodecStr,
                audioMuxerCodec,
                channels: Math.min(2, audioBuffer.numberOfChannels),
                sampleRate: audioBuffer.sampleRate,
              }
            : undefined,
      });

      // Await worker initialization and codec configuration before proceeding
      await initWorkerPromise;

      // Encode audio chunks if available
      if (canEncodeAudio && audioBuffer) {
        onProgress({
          percentage: 2,
          currentTime: 0,
          duration,
          status: 'Mã hóa audio trong Web Worker...',
        });

        const sampleRate = audioBuffer.sampleRate;
        const channels = Math.min(2, audioBuffer.numberOfChannels);
        const frameSize = 1024;
        const totalSamples = audioBuffer.length;
        const chan0 = audioBuffer.getChannelData(0);
        const chan1 = channels > 1 ? audioBuffer.getChannelData(1) : chan0;

        for (let offset = 0; offset < totalSamples; offset += frameSize) {
          const numFrames = Math.min(frameSize, totalSamples - offset);
          const interleaved = new Float32Array(numFrames * channels);
          for (let i = 0; i < numFrames; i++) {
            interleaved[i * channels] = chan0[offset + i];
            if (channels > 1) {
              interleaved[i * channels + 1] = chan1[offset + i];
            }
          }
          const timestampUs = Math.round((offset / sampleRate) * 1_000_000);

          worker.postMessage(
            {
              type: 'ENCODE_AUDIO_DATA',
              sampleRate,
              channels,
              numberOfFrames: numFrames,
              timestampUs,
              data: interleaved,
            },
            [interleaved.buffer]
          );
        }
      }

      let processedFrames = 0;
      let nextFrameToEncodeIdx = 0;
      let isDecoderFlushed = false;
      completedFramesMap = new Map<number, {
        renderedBitmap: ImageBitmap;
        timestampUs: number;
        isKeyFrame: boolean;
        currentTime: number;
      }>();

      // Initialize Task Worker Pool for Parallel Subtitle/Overlays Rendering
      const numWorkers = Math.min(navigator.hardwareConcurrency || 4, 4);
      const MAX_IN_FLIGHT_FRAMES = Math.min(16, numWorkers * 4);
      taskWorkers = [];

      const finalizeEncoding = () => {
        if (typeof watchdogInterval !== 'undefined') {
          clearInterval(watchdogInterval);
        }
        if (worker) {
          worker.postMessage({ type: 'FINALIZE' });
        }
        // Cleanup task workers
        taskWorkers.forEach(tw => tw.terminate());
      };

      const processCompletedFramesQueue = () => {
        if (!completedFramesMap) return;
        while (completedFramesMap.has(nextFrameToEncodeIdx)) {
          const item = completedFramesMap.get(nextFrameToEncodeIdx)!;
          completedFramesMap.delete(nextFrameToEncodeIdx);

          if (worker) {
            worker.postMessage(
              {
                type: 'ENCODE_FRAME',
                renderedBitmap: item.renderedBitmap,
                timestampUs: item.timestampUs,
                isKeyFrame: item.isKeyFrame,
                currentTime: item.currentTime,
                frameIdx: nextFrameToEncodeIdx,
                totalFrames: totalFrames, // Use fixed actual total frame count demuxed from MP4
              },
              [item.renderedBitmap]
            );
          } else {
            item.renderedBitmap.close();
          }

          nextFrameToEncodeIdx++;
        }

        if (isDecoderFlushed && nextFrameToEncodeIdx === processedFrames) {
          finalizeEncoding();
        }
      };

      for (let i = 0; i < numWorkers; i++) {
        const tw = new Worker(
          new URL('../workers/videoRenderTask.worker.ts', import.meta.url),
          { type: 'module' }
        );
        tw.onmessage = (msg: MessageEvent) => {
          const { type, renderedBitmap, frameIdx, timestampUs, isKeyFrame, currentTime, error } = msg.data;
          if (type === 'RENDER_DONE') {
            completedFramesMap.set(frameIdx, {
              renderedBitmap,
              timestampUs,
              isKeyFrame,
              currentTime,
            });
            processCompletedFramesQueue();
          } else if (type === 'RENDER_ERROR') {
            console.error(`[Render Worker Pool] Error on frame ${frameIdx}:`, error);
            reject(new Error(error || `Render worker failed on frame ${frameIdx}`));
            taskWorkers.forEach(w => w.terminate());
          }
        };
        tw.onerror = (err) => {
          reject(new Error(`Render Worker Pool error: ${err.message}`));
          taskWorkers.forEach(w => w.terminate());
        };
        taskWorkers.push(tw);
      }

      // Safety watchdog timer: If nextFrameToEncodeIdx is blocked for over 8 seconds while frames are pending, throw clear timeout error
      let lastProgressTime = Date.now();
      let lastFrameIdxCheck = -1;
      watchdogInterval = setInterval(() => {
        if (nextFrameToEncodeIdx > lastFrameIdxCheck) {
          lastFrameIdxCheck = nextFrameToEncodeIdx;
          lastProgressTime = Date.now();
        } else if (processedFrames > nextFrameToEncodeIdx) {
          if (Date.now() - lastProgressTime > 8000) {
            clearInterval(watchdogInterval);
            console.error(`[Render Watchdog] Pipeline stalled waiting for frame ${nextFrameToEncodeIdx} (Processed: ${processedFrames})`);
            taskWorkers.forEach(w => w.terminate());
            reject(new Error(`Quá trình render bị treo tại khung hình ${nextFrameToEncodeIdx + 1}/${totalFrames}. Vui lòng thử lại.`));
          }
        }
      }, 1000);

      const decodingBuffer: VideoFrame[] = [];

      const processNextDecodedFrame = (force = false) => {
        // We want to keep at most 12 frames in the buffer to reorder B-frames or out-of-order decode packets
        const threshold = force ? 0 : 12;
        while (decodingBuffer.length > threshold) {
          // Sort the buffer by timestamp so output DTS/PTS is strictly monotonically increasing
          decodingBuffer.sort((a, b) => a.timestamp - b.timestamp);
          
          const frame = decodingBuffer.shift()!;
          const frameIdx = processedFrames;
          const keyframeInterval = Math.max(1, Math.round(videoFps * 2));
          const isKeyFrame = frameIdx % keyframeInterval === 0;
          const currentTime = frameIdx / videoFps;
          const timestampUs = Math.round((frameIdx / videoFps) * 1_000_000);

          processedFrames++;

          // Assign rendering work to task worker round-robin
          const targetWorker = taskWorkers[frameIdx % numWorkers];
          targetWorker.postMessage(
            {
              type: 'RENDER',
              videoFrame: frame,
              timestampUs,
              isKeyFrame,
              currentTime,
              vWidth,
              vHeight,
              subtitles,
              styleConfig,
              frameIdx,
              blurOverlays: options.blurOverlays,
              logoOverlays: options.logoOverlays,
              textOverlays: options.textOverlays,
            },
            [frame]
          );
        }
      };

      const decoder = new VideoDecoder({
        output: (frame: VideoFrame) => {
          try {
            decodingBuffer.push(frame);
            processNextDecodedFrame(false);
          } catch (err) {
            console.error('Lỗi xử lý khung hình:', err);
            frame.close();
          }
        },
        error: (err) => {
          console.error('Lỗi VideoDecoder khi render:', err);
          taskWorkers.forEach(w => w.terminate());
          reject(err);
        },
      });

      // Configure decoder
      try {
        decoder.configure(decoderConfig);
      } catch (_cfgErr) {
        const altConfig = { ...decoderConfig };
        delete (altConfig as any).description;
        decoder.configure(altConfig);
      }

      // Feed demuxed samples sequentially with bounded backpressure on decoder queue AND total in-flight frames
      const MAX_DECODE_QUEUE = 12;
      for (const sample of accumulatedSamples) {
        if (hasWorkerError) {
          throw new Error(workerErrorMessage || 'Mã hóa video bị lỗi trong worker.');
        }

        while (
          decoder.decodeQueueSize > MAX_DECODE_QUEUE ||
          (processedFrames - nextFrameToEncodeIdx >= MAX_IN_FLIGHT_FRAMES)
        ) {
          if (hasWorkerError) {
            throw new Error(workerErrorMessage || 'Mã hóa video bị lỗi trong worker.');
          }

          await new Promise<void>((resolve) => {
            const checkAndResolve = () => {
              if (
                hasWorkerError ||
                (decoder.decodeQueueSize <= MAX_DECODE_QUEUE / 2 &&
                (processedFrames - nextFrameToEncodeIdx < MAX_IN_FLIGHT_FRAMES))
              ) {
                decoder.ondequeue = null;
                resolve();
              }
            };
            decoder.ondequeue = checkAndResolve;
            const timer = setTimeout(() => {
              checkAndResolve();
              clearTimeout(timer);
            }, 6);
          });
        }

        const ts = Math.round((sample.cts * 1_000_000) / sample.timescale);
        const dur = Math.round((sample.duration * 1_000_000) / sample.timescale);

        decoder.decode(new EncodedVideoChunk({
          type: sample.is_sync ? 'key' : 'delta',
          timestamp: ts,
          duration: dur,
          data: sample.data,
        }));
      }

      await decoder.flush();
      processNextDecodedFrame(true);
      decoder.close();
      isDecoderFlushed = true;

      if (nextFrameToEncodeIdx === processedFrames) {
        finalizeEncoding();
      } else {
        processCompletedFramesQueue();
      }

      const finalMp4Blob = await workerPromise;
      if (worker) {
        worker.terminate();
        worker = null;
      }
      resolve(finalMp4Blob);
    } catch (err) {
      if (typeof watchdogInterval !== 'undefined') {
        clearInterval(watchdogInterval);
      }
      if (typeof completedFramesMap !== 'undefined') {
        completedFramesMap.forEach((item) => {
          if (item?.renderedBitmap && typeof item.renderedBitmap.close === 'function') {
            item.renderedBitmap.close();
          }
        });
        completedFramesMap.clear();
      }
      if (typeof taskWorkers !== 'undefined' && Array.isArray(taskWorkers)) {
        taskWorkers.forEach(tw => tw.terminate());
      }
      if (worker) {
        worker.terminate();
        worker = null;
      }
      reject(err);
    }
  });
}

async function preloadLogoOverlays(logoOverlays: LogoOverlay[]): Promise<Record<string, HTMLImageElement>> {
  const logoBitmaps: Record<string, HTMLImageElement> = {};
  await Promise.all(
    logoOverlays.map(async (logo) => {
      try {
        const img = new Image();
        img.crossOrigin = 'anonymous';
        img.src = logo.url;
        await new Promise((resolve, reject) => {
          img.onload = resolve;
          img.onerror = reject;
        });
        logoBitmaps[logo.id] = img;
        logoBitmaps[logo.url] = img;
      } catch (err) {
        console.warn(`[Preload Logos] Unable to preload logo from ${logo.url}:`, err);
      }
    })
  );
  return logoBitmaps;
}

/**
 * Fallback recorder using standard browser MediaRecorder API (WebM/MP4).
 */
export async function renderWithMediaRecorder(
  videoUrl: string,
  subtitles: SubtitleItem[],
  styleConfig: SubtitleStyleConfig,
  onProgress: (progress: RenderProgress) => void,
  options: {
    blurOverlays?: BlurOverlay[];
    logoOverlays?: LogoOverlay[];
    textOverlays?: TextOverlay[];
    includeVoiceover?: boolean;
    ttsSpeed?: number;
    ttsPitch?: number;
    videoVolume?: number;
    preferredFormat?: 'mp4' | 'webm';
  } = {}
): Promise<Blob> {
  return new Promise(async (resolve, reject) => {
    const video = document.createElement('video');
    if (videoUrl && !videoUrl.startsWith('blob:')) {
      video.crossOrigin = 'anonymous';
    }
    video.src = videoUrl;
    video.muted = true; // Mute video element to guarantee video.play() never gets blocked by autoplay policy

    // Preload logo images for MediaRecorder canvas overlay
    const logoBitmaps = options.logoOverlays ? await preloadLogoOverlays(options.logoOverlays) : {};

    video.onloadedmetadata = async () => {
      try {
        const vWidth = video.videoWidth || 1280;
        const vHeight = video.videoHeight || 720;
        const duration = video.duration || 10;

        const canvas = document.createElement('canvas');
        canvas.width = vWidth;
        canvas.height = vHeight;
        const ctx = canvas.getContext('2d');

        if (!ctx) {
          reject(new Error('Không thể khởi tạo Canvas 2D'));
          return;
        }

        // Fetch original audio track and decode it
        let originalAudioBuffer: AudioBuffer | null = null;
        try {
          const res = await fetch(videoUrl);
          if (res.ok) {
            const arrBuf = await res.arrayBuffer();
            const actx = new (window.AudioContext || (window as any).webkitAudioContext)();
            originalAudioBuffer = await actx.decodeAudioData(arrBuf);
            await actx.close();
          }
        } catch (e) {
          console.warn('[MediaRecorder Fallback] Không có hoặc không nạp được audio track gốc:', e);
        }

        // Synthesize and mix voiceover audio track if requested
        const videoVolume = options.videoVolume ?? 1.0;
        let audioBuffer: AudioBuffer | null = null;
        if (options.includeVoiceover) {
          try {
            const result = await generateVoiceoverAudioBuffer(
              subtitles,
              duration,
              options.ttsSpeed || 1.0,
              options.ttsPitch || 0
            );
            const ttsAudioBuffer = result.buffer;
            audioBuffer = await mixAudioBuffers(originalAudioBuffer, ttsAudioBuffer, duration, videoVolume);
          } catch (e) {
            console.warn('[MediaRecorder Fallback] Không thể dựng audio thuyết minh, sẽ dùng audio gốc:', e);
            audioBuffer = await adjustAudioBufferVolume(originalAudioBuffer, videoVolume, duration);
          }
        } else {
          audioBuffer = await adjustAudioBufferVolume(originalAudioBuffer, videoVolume, duration);
        }

        const AudioCtx = window.AudioContext || (window as any).webkitAudioContext;
        const audioCtx = new AudioCtx();
        const dest = audioCtx.createMediaStreamDestination();

        // Ensure the AudioContext is running (important inside sandboxed iframes)
        if (audioCtx.state === 'suspended') {
          await audioCtx.resume();
        }

        let audioSourceNode: AudioBufferSourceNode | null = null;
        if (audioBuffer) {
          audioSourceNode = audioCtx.createBufferSource();
          audioSourceNode.buffer = audioBuffer;
          audioSourceNode.connect(dest);
        }

        const canvasStream = canvas.captureStream(30);
        const combinedTracks = [...canvasStream.getVideoTracks()];
        if (audioBuffer) {
          combinedTracks.push(...dest.stream.getAudioTracks());
        }
        const combinedStream = new MediaStream(combinedTracks);

        let mimeType = '';
        const prefFormat = options.preferredFormat || 'mp4';

        if (prefFormat === 'mp4') {
          if (MediaRecorder.isTypeSupported('video/mp4;codecs=h264,aac')) {
            mimeType = 'video/mp4;codecs=h264,aac';
          } else if (MediaRecorder.isTypeSupported('video/mp4')) {
            mimeType = 'video/mp4';
          }
        }

        if (!mimeType) {
          if (MediaRecorder.isTypeSupported('video/webm;codecs=vp9,opus')) {
            mimeType = 'video/webm;codecs=vp9,opus';
          } else if (MediaRecorder.isTypeSupported('video/webm;codecs=vp8,opus')) {
            mimeType = 'video/webm;codecs=vp8,opus';
          } else if (MediaRecorder.isTypeSupported('video/webm')) {
            mimeType = 'video/webm';
          } else if (MediaRecorder.isTypeSupported('video/mp4;codecs=h264,aac')) {
            mimeType = 'video/mp4;codecs=h264,aac';
          } else if (MediaRecorder.isTypeSupported('video/mp4')) {
            mimeType = 'video/mp4';
          }
        }

        const recorderOptions = mimeType ? { mimeType } : undefined;
        const recorder = new MediaRecorder(combinedStream, recorderOptions);
        const chunks: Blob[] = [];

        recorder.ondataavailable = (e) => {
          if (e.data && e.data.size > 0) {
            chunks.push(e.data);
          }
        };

        recorder.onstop = async () => {
          if (audioSourceNode) {
            try { audioSourceNode.stop(); } catch {}
          }
          const finalType = mimeType || 'video/webm';
          const rawBlob = new Blob(chunks, { type: finalType });
          const durationMs = Math.max(1000, Math.round(duration * 1000));
          const durationSec = duration;

          if (finalType.includes('webm')) {
            try {
              fixWebmDuration(rawBlob, durationMs, (fixedBlob) => {
                resolve(fixedBlob);
              });
              return;
            } catch (fixErr) {
              console.warn('[MediaRecorder] Failed to fix webm duration header:', fixErr);
            }
          } else if (finalType.includes('mp4')) {
            try {
              const fixedBlob = await fixMp4Duration(rawBlob, durationSec);
              resolve(fixedBlob);
              return;
            } catch (fixErr) {
              console.warn('[MediaRecorder] Failed to fix mp4 duration header:', fixErr);
            }
          }
          resolve(rawBlob);
        };

        recorder.onerror = (err) => {
          reject(err);
        };

        const renderFrame = () => {
          const curTime = video.currentTime;
          const pct = Math.min(100, Math.round((curTime / duration) * 100));

          onProgress({
            percentage: pct,
            currentTime: curTime,
            duration,
            status: `Đang render video... (${pct}%)`,
          });

          drawSubtitleOverlay(
            ctx,
            video,
            vWidth,
            vHeight,
            curTime,
            subtitles,
            styleConfig,
            options.blurOverlays,
            options.logoOverlays,
            options.textOverlays,
            logoBitmaps
          );

          if (!video.ended && video.currentTime < duration) {
            requestAnimationFrame(renderFrame);
          } else {
            setTimeout(() => {
              if (recorder.state === 'recording') {
                recorder.stop();
              }
            }, 300);
          }
        };

        recorder.start(1000); // Pass timeslice to record chunks progressively and prevent Infinity duration issues
        
        video.play().then(() => {
          if (audioSourceNode) {
            audioSourceNode.start(0);
          }
          renderFrame();
        }).catch((playErr) => {
          console.error('[MediaRecorder Fallback] video.play() failed:', playErr);
          reject(new Error(`Không thể phát video để ghi hình: ${playErr.message}`));
        });

        video.onended = () => {
          setTimeout(() => {
            if (recorder.state === 'recording') {
              recorder.stop();
            }
          }, 300);
        };
      } catch (err) {
        reject(err);
      }
    };

    video.onerror = () => {
      reject(new Error('Không thể tải video nguồn để render.'));
    };
  });
}

/**
 * Main export video entry point. Uses mp4-muxer for MP4 format when supported,
 * with graceful fallback to MediaRecorder.
 */
export async function renderVideoWithSubtitles(
  videoUrl: string,
  subtitles: SubtitleItem[],
  styleConfig: SubtitleStyleConfig,
  onProgress: (progress: RenderProgress) => void,
  preferredFormat: 'mp4' | 'webm' | 'mediarecorder' = 'mp4',
  options: {
    blurOverlays?: BlurOverlay[];
    logoOverlays?: LogoOverlay[];
    textOverlays?: TextOverlay[];
    includeVoiceover?: boolean;
    ttsSpeed?: number;
    ttsPitch?: number;
    videoVolume?: number;
  } = {}
): Promise<{ blob: Blob; formatUsed: 'mp4' | 'webm' }> {
  if (preferredFormat === 'mp4' && typeof VideoEncoder !== 'undefined') {
    try {
      const blob = await renderWithMp4Muxer(videoUrl, subtitles, styleConfig, onProgress, options, false);
      return { blob, formatUsed: 'mp4' };
    } catch (err: any) {
      console.warn('[Mediabunny] GPU/HW rendering failed, retrying with Software Encoder (prefer-software)...', err);
      onProgress({
        percentage: 0,
        currentTime: 0,
        duration: 1,
        status: 'GPU encoder gián đoạn, đang tự động thử lại bằng Software Encoder (CPU)...',
      });
      try {
        const blob = await renderWithMp4Muxer(videoUrl, subtitles, styleConfig, onProgress, options, true);
        return { blob, formatUsed: 'mp4' };
      } catch (retryErr: any) {
        console.warn('[Mediabunny] Software rendering failed too, falling back to MediaRecorder:', retryErr);
        onProgress({
          percentage: 0,
          currentTime: 0,
          duration: 1,
          status: 'Chuyển sang MediaRecorder fallback...',
        });
      }
    }
  }

  const blob = await renderWithMediaRecorder(videoUrl, subtitles, styleConfig, onProgress, {
    ...options,
    preferredFormat: preferredFormat === 'webm' ? 'webm' : 'mp4',
  });
  const formatUsed = blob.type.includes('mp4') ? 'mp4' : 'webm';
  return { blob, formatUsed };
}
